### ISSUE TITLE
Incorrect request method when Authorizing or not Authorizing

### ISSUE THREAD

**Issue by britweb-tim** [co-cart/cocart-js-lib#106]
Since updating to 3.0.3 (from 2.x) I can no longer add to cart via a react component (using the @cocart/cocart-rest-api library).  I'm suddenly getting a 401 error from the server.

Response is: 
`
{"code":"woocommerce_rest_authentication_missing_parameter","message":"Missing OAuth parameter oauth_consumer_key","data":{"status":401}}
`

Any ideas?  I thought at first it was due to be operating on a local dev server (not https), but the same issue occurs over https as well.

Request (cURL) is along the lines of: 

```
curl 'https://mysite.foo/wp-json/cocart/v2/add-item?oauth_consumer_key=&oauth_nonce=H8zvy7kyYv6Czv395G4ck87ASnwHRnc0&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1621259305&oauth_version=1.0&oauth_signature=Id5SYwKgg8FWXwREMoqsse7ev5N5mZjRbIvzKGqjrJ0%3D' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"' \
  -H 'Accept: application/json' \
  -H 'DNT: 1' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Origin: https://mysite.foo' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://mysite.foo/product/teamwear/socks-teamwear/full-length-socks/' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Cookie: _ga=GA1.3.968707277.1591347534; cookielawinfo-checkbox-non-necessary=yes; cookielawinfo-checkbox-necessary=yes; viewed_cookie_policy=yes; CookieLawInfoConsent=eyJuZWNlc3NhcnkiOnRydWUsIm5vbi1uZWNlc3NhcnkiOnRydWV9; wp-settings-1=libraryContent%3Dbrowse; _fbp=fb.2.1610448280180.1841253780; wp-settings-time-1=1620288912; _gcl_au=1.1.1712335327.1620838761; woocommerce_items_in_cart=1; woocommerce_cart_hash=7cb4c4f4bc7decf39ec9d45b450c50c0; wp_cocart_session_e166e212aa264c65fd64411d789d41b0=1%7C%7C1621861183%7C%7C1621774783%7C%7Ced37fc15784116f6f331d3a1fba9be8a; wordpress_test_cookie=WP+Cookie+check; wordpress_logged_in_e166e212aa264c65fd64411d789d41b0=britweb-mdhtw%7C1621429306%7CIpEHRXRpWT3AWskl7GezkwfbjOBlgjzn1NmDY7i3Z9g%7Cacc2705fd4154f40165ae969ccc2be075bb688bef5f604bd536650863c96c0e9; tk_ai=woo%3ARTLZgaY3TlPi%2Fog01f1y%2FxrV' \
  --data-raw '{"key":"cartkosnw871","product_id":"100593","quantity":"1","variation_id":100608,"variation":{"size":"X-Small"},"cart_item_data":{"order_part_key":"kosnxi6f","addons":[],"playerData":[{"size":"X-Small","values":{}}],"variant_price":13,"variant_size":"X-Small"}}' \
  --compressed
```

**Comment by seb86** [comment]
Also, are you still able to access API v1 without issues using the JS lib?

**Comment by britweb-tim** [comment]
I get the same error when I switch to v1.

**Comment by britweb-tim** [comment]
WooCommerce is v5.3.0. cocart-js-lib is v1.0.1.

My script is a little tricky to explain, but it basically ads multiple variants at once, so we've got a trigger function which sets up the data, and then an "inner" function which goes through the cart items to be added.

```javascript
   /**
     * Add the selected products to the cart.
     */
    addToCart(context) {
        this.setState({addingToCart:true});
        // Get the cart key
        const cookies = new Cookies();
        let cartKey = cookies.get('cart_key');
        if(!cartKey) {
            cartKey = uniqid('cart');
            cookies.set('cart_key', cartKey, {
                domain:"",
                secure:false
            });
        }

        const orderPartKey = uniqid();

        let cartItems = [];
        context.availableVariants.map((variant) => {
            if(variant.quantity) {
                let newItem = {
                    "key":cartKey,
                    "product_id":this.props.productId,
                    "quantity":variant.quantity,
                    "variation_id":variant.id,
                    "variation": variant.attributes,
                    "cart_item_data":{
                        "order_part_key": orderPartKey,
                        "addons":context.selectedAddons,
                        "playerData":context.playerData,
                        "variant_price":context.getVariantTotalPerUnit(variant),
                        "variant_size":variant.name
                    }
                }
                cartItems.push(newItem);
            }
        })
        let iter = 0;
        this.addToCartInner(cartItems, iter);

    }

    /**
     * Sequentially add all cartitems to the cart
     */
    addToCartInner(cartItems, iter) {
        const CoCart = new CoCartAPI({
            url:this.state.baseUrl
        });
        CoCart.post('add-item', cartItems[iter])
            .then((data)=>{
                iter++;
                if(iter < cartItems.length) {
                    this.addToCartInner(cartItems, iter);
                }
                else {
                    this.setState({addingToCart:false,inCart:true});
                }
            });
    }
```

**Comment by seb86** [comment]
You need to update your parameters when adding item to cart. Product ID is now just ID. No longer need to put variation id seperate. Just put the variation id in the ID parameter.

**Comment by seb86** [comment]
Do you get the same error response when using any of the REST API tools i have listed in the docs?

**Comment by britweb-tim** [comment]
Okay, tried in Postman.  Seems to be working there.

In browser (through the API), it's pushing a bunch of oauth url parameters

POSTing to this url works : http://localhost:8080/wp-json/cocart/v2/cart/add-item

The url the cocart-rest-api is generating is this : http://localhost:8080/wp-json/cocart/v2/cart/add-item?oauth_consumer_key=&oauth_nonce=vMgYErJc97jwuxgotldWYWpoc4Quc2z3&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1621268976&oauth_version=1.0&oauth_signature=Hu3D9OJp2kSyTeGSId8eWyJoNsFsxtbp6FgP2iVMktI%3D

Looking at the woocommerce code (WC_REST_Authentication::get_oauth_parameters()) , if any oauth parameters are set and any one of them is missing it returns the error "woocommerce_rest_authentication_missing_parameter"

**Comment by seb86** [comment]
OK i will see about removing the added url parameters generated. The JS lib was forked from WC JS lib so im still tweaking. Thank you for your report.

**Comment by britweb-tim** [comment]
Okay, I'll try to piece this together with a plain old fetch for now.

**Comment by seb86** [comment]
@britweb-tim Did you have `queryStringAuth` parameter set?

**Comment by britweb-tim** [comment]
No, didn't set it intentionally.  Tried forcing it to false in the constructor but no effect.  Worth noting that I hadn't updated the JS API, so this may be something related to WooCommerce 5.3,0.

I seem to have it working without the API now, at least works for guests.  Have yet to check for authenticated users.

**Comment by petarneykov1984** [comment]
@seb86 I can confirm I have exactly the same as above issue:(

**Comment by seb86** [comment]
@britweb-tim @pnikolov @petarneykov1984 I have pushed a change I hope that works better on the master branch. Still fixing the testsuite. Would you mind checking to see if it helps, I appreciate your feedback. Thank you.

**Comment by pnikolov** [comment]
@seb86 Thanks for the quick update and the documentation update!

The change for `v1.1.0` is working as expected when using non HTTPS API - great! But I see the code still passes `consumerKey` and `consumerSecret` in the case `this.isHttps` is `true` which will again trigger the API authentication logic(_Basic auth_), regardless of the fact when you do not need authentication (_the guest case_).

**Comment by seb86** [comment]
@pnikolov I see what I have done wrong. Placed an if statement in the wrong order for HTTPS

Next push should fix that.

**Comment by seb86** [comment]
Build passed tests again. Should be all good now. Look forward to your feedback.

@britweb-tim @pnikolov @petarneykov1984
