### ISSUE TITLE
cocart X-CoCart-API key is not working in React

### ISSUE THREAD

**Issue by sifulbd** [co-cart/cocart-js-lib#86]
I tried to post an item using CoCart and get the cart_key to fetch data. 
I tried but it only shows "Content-Type": "application/json",

**Comment by seb86** [comment]
The information provided here is very vague @sifulbd 

Are you not able to fetch any headers or just `X-CoCart-API` header?

**Comment by seb86** [comment]
You should be able to get the data object which also passes the responses headers in a separate object so you can do response.data for the data or response.headers to view all the headers.

**Comment by sifulbd** [comment]
I tried in all ways. I can fetch hearder. I am not able to fetch just X-CoCart-API header.
You can see my response here: https://prnt.sc/117320v

**Comment by seb86** [comment]
You will need to set the `axiosConfig` option and tell it to set `withCredentials` as `true`. This should return all headers.

[Options to config Axios](https://github.com/axios/axios#request-config).

**Comment by sifulbd** [comment]
Thank you for you text.
I tried with `axiosConfig ` but it seems the same result.

![Screenshot_12](https://user-images.githubusercontent.com/8652443/114074606-5f045c80-98c6-11eb-91ea-78f4a3d8ae41.png)

The out put is same :  https://prnt.sc/117ij0a

**Comment by seb86** [comment]
That is odd. [The header](https://github.com/co-cart/co-cart/blob/v2.9.2/includes/class-cocart-authentication.php#L337) is exposed so it should be returning.

**Comment by seb86** [comment]
[This article](https://stackoverflow.com/questions/37897523/axios-get-access-to-response-header-fields) may help.

**Comment by seb86** [comment]
If you were only not getting `X-CoCart-API` header then I could look into it more but your not getting any other headers that should return by default.

**Comment by seb86** [comment]
@sifulbd What version of CoCart are you using?

**Comment by sifulbd** [comment]
Hi, 
sorry for the delayed response. 
I am getting the other headers except `X-CoCart-API` . 
I am using `cocart/cocart-rest-api: ^1.0.1` version.

**Comment by sifulbd** [comment]
I have created a code sandbox. I hope you can check it live:  [codesandbox link ](https://codesandbox.io/s/red-water-nuckb?file=/pages/index.js )

**Comment by seb86** [comment]
> Hi, 
> sorry for the delayed response. 
> I am getting the other headers except `X-CoCart-API` . 
> I am using `cocart/cocart-rest-api: ^1.0.1` version. 

I was referring to the version of the CoCart plugin not the JS wrapper.

**Comment by sifulbd** [comment]
> > Hi,
> > sorry for the delayed response.
> > I am getting the other headers except `X-CoCart-API` .
> > I am using `cocart/cocart-rest-api: ^1.0.1` version.
> 
> I was referring to the version of the CoCart plugin not the JS wrapper.

`Version 2.9.1`

**Comment by seb86** [comment]
I don't know if it will help but would you mind updating to v2.9.2 as it is a hotfix. It might correct the header returning.

**Comment by sifulbd** [comment]
no luck

**Comment by seb86** [comment]
I forked your sandbox and tested with my demo site. It returned no problem so it looks like you have not enabled CORS with CoCart. This can be done via the filter `cocart_disable_all_cors` which is in the documentation. Or you can [install the CORS plugin](https://wordpress.org/plugins/cocart-cors/) if you don't know PHP.
